name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy to EC2
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Upload your app files to the EC2 instance
        scp -i key.pem -r . ec2-user@${{ secrets.EC2_INSTANCE_IP }}:~/app

        # SSH into the EC2 instance and execute deployment commands
        ssh -i key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} "cd ~/app && ./deploy.sh"

